# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created: Tue Oct  3 08:56:27 2017
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1260, 577)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1226, 542))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout_3 = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.DataFileName_ledt = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataFileName_ledt.sizePolicy().hasHeightForWidth())
        self.DataFileName_ledt.setSizePolicy(sizePolicy)
        self.DataFileName_ledt.setMinimumSize(QtCore.QSize(400, 0))
        self.DataFileName_ledt.setObjectName(_fromUtf8("DataFileName_ledt"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.DataFileName_ledt)
        self.DataFile_btn = QtGui.QPushButton(self.groupBox_3)
        self.DataFile_btn.setObjectName(_fromUtf8("DataFile_btn"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.DataFile_btn)
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.groupBox_3)
        self.groupBox_9 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.peakRadius_lbl = QtGui.QLabel(self.groupBox_9)
        self.peakRadius_lbl.setObjectName(_fromUtf8("peakRadius_lbl"))
        self.gridLayout_6.addWidget(self.peakRadius_lbl, 0, 0, 1, 1)
        self.peakRadius_ledt = QtGui.QLineEdit(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peakRadius_ledt.sizePolicy().hasHeightForWidth())
        self.peakRadius_ledt.setSizePolicy(sizePolicy)
        self.peakRadius_ledt.setObjectName(_fromUtf8("peakRadius_ledt"))
        self.gridLayout_6.addWidget(self.peakRadius_ledt, 0, 1, 1, 1)
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.groupBox_9)
        self.groupBox_4 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.CalFileName_ledt = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CalFileName_ledt.sizePolicy().hasHeightForWidth())
        self.CalFileName_ledt.setSizePolicy(sizePolicy)
        self.CalFileName_ledt.setMinimumSize(QtCore.QSize(400, 0))
        self.CalFileName_ledt.setObjectName(_fromUtf8("CalFileName_ledt"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.CalFileName_ledt)
        self.CalFile_btn = QtGui.QPushButton(self.groupBox_4)
        self.CalFile_btn.setObjectName(_fromUtf8("CalFile_btn"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.CalFile_btn)
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.groupBox_4)
        self.groupBox_7 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.linScatt_lbl = QtGui.QLabel(self.groupBox_7)
        self.linScatt_lbl.setObjectName(_fromUtf8("linScatt_lbl"))
        self.gridLayout_4.addWidget(self.linScatt_lbl, 0, 2, 1, 1)
        self.linAbs_ledt = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linAbs_ledt.sizePolicy().hasHeightForWidth())
        self.linAbs_ledt.setSizePolicy(sizePolicy)
        self.linAbs_ledt.setObjectName(_fromUtf8("linAbs_ledt"))
        self.gridLayout_4.addWidget(self.linAbs_ledt, 0, 5, 1, 1)
        self.sampleRadius_ledt = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleRadius_ledt.sizePolicy().hasHeightForWidth())
        self.sampleRadius_ledt.setSizePolicy(sizePolicy)
        self.sampleRadius_ledt.setObjectName(_fromUtf8("sampleRadius_ledt"))
        self.gridLayout_4.addWidget(self.sampleRadius_ledt, 0, 1, 1, 1)
        self.linAbs_lbl = QtGui.QLabel(self.groupBox_7)
        self.linAbs_lbl.setObjectName(_fromUtf8("linAbs_lbl"))
        self.gridLayout_4.addWidget(self.linAbs_lbl, 0, 4, 1, 1)
        self.powerWavelength_lbl = QtGui.QLabel(self.groupBox_7)
        self.powerWavelength_lbl.setObjectName(_fromUtf8("powerWavelength_lbl"))
        self.gridLayout_4.addWidget(self.powerWavelength_lbl, 0, 6, 1, 1)
        self.powerWavelength_ledt = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powerWavelength_ledt.sizePolicy().hasHeightForWidth())
        self.powerWavelength_ledt.setSizePolicy(sizePolicy)
        self.powerWavelength_ledt.setObjectName(_fromUtf8("powerWavelength_ledt"))
        self.gridLayout_4.addWidget(self.powerWavelength_ledt, 0, 7, 1, 1)
        self.sampleRadius_lbl = QtGui.QLabel(self.groupBox_7)
        self.sampleRadius_lbl.setObjectName(_fromUtf8("sampleRadius_lbl"))
        self.gridLayout_4.addWidget(self.sampleRadius_lbl, 0, 0, 1, 1)
        self.linScatt_ledt = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linScatt_ledt.sizePolicy().hasHeightForWidth())
        self.linScatt_ledt.setSizePolicy(sizePolicy)
        self.linScatt_ledt.setObjectName(_fromUtf8("linScatt_ledt"))
        self.gridLayout_4.addWidget(self.linScatt_ledt, 0, 3, 1, 1)
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.groupBox_7)
        self.groupBox_10 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.minIntensity_lbl = QtGui.QLabel(self.groupBox_10)
        self.minIntensity_lbl.setObjectName(_fromUtf8("minIntensity_lbl"))
        self.gridLayout_7.addWidget(self.minIntensity_lbl, 0, 0, 1, 1)
        self.minIntensity_ledt = QtGui.QLineEdit(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minIntensity_ledt.sizePolicy().hasHeightForWidth())
        self.minIntensity_ledt.setSizePolicy(sizePolicy)
        self.minIntensity_ledt.setObjectName(_fromUtf8("minIntensity_ledt"))
        self.gridLayout_7.addWidget(self.minIntensity_ledt, 0, 1, 1, 1)
        self.numberGridPoints_lbl = QtGui.QLabel(self.groupBox_10)
        self.numberGridPoints_lbl.setObjectName(_fromUtf8("numberGridPoints_lbl"))
        self.gridLayout_7.addWidget(self.numberGridPoints_lbl, 0, 2, 1, 1)
        self.numberGridPoints_ledt = QtGui.QLineEdit(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberGridPoints_ledt.sizePolicy().hasHeightForWidth())
        self.numberGridPoints_ledt.setSizePolicy(sizePolicy)
        self.numberGridPoints_ledt.setObjectName(_fromUtf8("numberGridPoints_ledt"))
        self.gridLayout_7.addWidget(self.numberGridPoints_ledt, 0, 3, 1, 1)
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.groupBox_10)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.buttonBox)
        self.groupBox_8 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.PredictPeaks_rbtn = QtGui.QRadioButton(self.groupBox_8)
        self.PredictPeaks_rbtn.setObjectName(_fromUtf8("PredictPeaks_rbtn"))
        self.gridLayout_5.addWidget(self.PredictPeaks_rbtn, 0, 8, 1, 1)
        self.minABC_lbl = QtGui.QLabel(self.groupBox_8)
        self.minABC_lbl.setObjectName(_fromUtf8("minABC_lbl"))
        self.gridLayout_5.addWidget(self.minABC_lbl, 0, 2, 1, 1)
        self.numberPeaks_ledt = QtGui.QLineEdit(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberPeaks_ledt.sizePolicy().hasHeightForWidth())
        self.numberPeaks_ledt.setSizePolicy(sizePolicy)
        self.numberPeaks_ledt.setObjectName(_fromUtf8("numberPeaks_ledt"))
        self.gridLayout_5.addWidget(self.numberPeaks_ledt, 0, 1, 1, 1)
        self.maxABC_ledt = QtGui.QLineEdit(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxABC_ledt.sizePolicy().hasHeightForWidth())
        self.maxABC_ledt.setSizePolicy(sizePolicy)
        self.maxABC_ledt.setObjectName(_fromUtf8("maxABC_ledt"))
        self.gridLayout_5.addWidget(self.maxABC_ledt, 0, 5, 1, 1)
        self.maxABC_lbl = QtGui.QLabel(self.groupBox_8)
        self.maxABC_lbl.setObjectName(_fromUtf8("maxABC_lbl"))
        self.gridLayout_5.addWidget(self.maxABC_lbl, 0, 4, 1, 1)
        self.tolerance_lbl = QtGui.QLabel(self.groupBox_8)
        self.tolerance_lbl.setObjectName(_fromUtf8("tolerance_lbl"))
        self.gridLayout_5.addWidget(self.tolerance_lbl, 0, 6, 1, 1)
        self.numberPeaks_lbl = QtGui.QLabel(self.groupBox_8)
        self.numberPeaks_lbl.setObjectName(_fromUtf8("numberPeaks_lbl"))
        self.gridLayout_5.addWidget(self.numberPeaks_lbl, 0, 0, 1, 1)
        self.tolerance_ledt = QtGui.QLineEdit(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tolerance_ledt.sizePolicy().hasHeightForWidth())
        self.tolerance_ledt.setSizePolicy(sizePolicy)
        self.tolerance_ledt.setObjectName(_fromUtf8("tolerance_ledt"))
        self.gridLayout_5.addWidget(self.tolerance_ledt, 0, 7, 1, 1)
        self.minABC_ledt = QtGui.QLineEdit(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minABC_ledt.sizePolicy().hasHeightForWidth())
        self.minABC_ledt.setSizePolicy(sizePolicy)
        self.minABC_ledt.setObjectName(_fromUtf8("minABC_ledt"))
        self.gridLayout_5.addWidget(self.minABC_ledt, 0, 3, 1, 1)
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.SpanningRole, self.groupBox_8)
        self.groupBox_5 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mindSpacing_lbl = QtGui.QLabel(self.groupBox_5)
        self.mindSpacing_lbl.setObjectName(_fromUtf8("mindSpacing_lbl"))
        self.horizontalLayout.addWidget(self.mindSpacing_lbl)
        self.mindSpacing_ledt = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mindSpacing_ledt.sizePolicy().hasHeightForWidth())
        self.mindSpacing_ledt.setSizePolicy(sizePolicy)
        self.mindSpacing_ledt.setObjectName(_fromUtf8("mindSpacing_ledt"))
        self.horizontalLayout.addWidget(self.mindSpacing_ledt)
        self.minWavelength_lbl = QtGui.QLabel(self.groupBox_5)
        self.minWavelength_lbl.setObjectName(_fromUtf8("minWavelength_lbl"))
        self.horizontalLayout.addWidget(self.minWavelength_lbl)
        self.minWavelength_ledt = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minWavelength_ledt.sizePolicy().hasHeightForWidth())
        self.minWavelength_ledt.setSizePolicy(sizePolicy)
        self.minWavelength_ledt.setObjectName(_fromUtf8("minWavelength_ledt"))
        self.horizontalLayout.addWidget(self.minWavelength_ledt)
        self.maxWavelength_lbl = QtGui.QLabel(self.groupBox_5)
        self.maxWavelength_lbl.setObjectName(_fromUtf8("maxWavelength_lbl"))
        self.horizontalLayout.addWidget(self.maxWavelength_lbl)
        self.maxWavelength_ledt = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxWavelength_ledt.sizePolicy().hasHeightForWidth())
        self.maxWavelength_ledt.setSizePolicy(sizePolicy)
        self.maxWavelength_ledt.setObjectName(_fromUtf8("maxWavelength_ledt"))
        self.horizontalLayout.addWidget(self.maxWavelength_ledt)
        self.minQspace_lbl = QtGui.QLabel(self.groupBox_5)
        self.minQspace_lbl.setObjectName(_fromUtf8("minQspace_lbl"))
        self.horizontalLayout.addWidget(self.minQspace_lbl)
        self.minQspace_ledt = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minQspace_ledt.sizePolicy().hasHeightForWidth())
        self.minQspace_ledt.setSizePolicy(sizePolicy)
        self.minQspace_ledt.setObjectName(_fromUtf8("minQspace_ledt"))
        self.horizontalLayout.addWidget(self.minQspace_ledt)
        self.maxQspace_lbl = QtGui.QLabel(self.groupBox_5)
        self.maxQspace_lbl.setObjectName(_fromUtf8("maxQspace_lbl"))
        self.horizontalLayout.addWidget(self.maxQspace_lbl)
        self.maxQspace_ledt = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxQspace_ledt.sizePolicy().hasHeightForWidth())
        self.maxQspace_ledt.setSizePolicy(sizePolicy)
        self.maxQspace_ledt.setObjectName(_fromUtf8("maxQspace_ledt"))
        self.horizontalLayout.addWidget(self.maxQspace_ledt)
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.SpanningRole, self.groupBox_5)
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.omega_ledt = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.omega_ledt.sizePolicy().hasHeightForWidth())
        self.omega_ledt.setSizePolicy(sizePolicy)
        self.omega_ledt.setObjectName(_fromUtf8("omega_ledt"))
        self.gridLayout_2.addWidget(self.omega_ledt, 0, 5, 1, 1)
        self.phi_lbl = QtGui.QLabel(self.groupBox)
        self.phi_lbl.setObjectName(_fromUtf8("phi_lbl"))
        self.gridLayout_2.addWidget(self.phi_lbl, 0, 0, 1, 1)
        self.phi_ledt = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phi_ledt.sizePolicy().hasHeightForWidth())
        self.phi_ledt.setSizePolicy(sizePolicy)
        self.phi_ledt.setObjectName(_fromUtf8("phi_ledt"))
        self.gridLayout_2.addWidget(self.phi_ledt, 0, 1, 1, 1)
        self.chi_ledt = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chi_ledt.sizePolicy().hasHeightForWidth())
        self.chi_ledt.setSizePolicy(sizePolicy)
        self.chi_ledt.setObjectName(_fromUtf8("chi_ledt"))
        self.gridLayout_2.addWidget(self.chi_ledt, 0, 3, 1, 1)
        self.omega_lbl = QtGui.QLabel(self.groupBox)
        self.omega_lbl.setObjectName(_fromUtf8("omega_lbl"))
        self.gridLayout_2.addWidget(self.omega_lbl, 0, 4, 1, 1)
        self.chi_lbl = QtGui.QLabel(self.groupBox)
        self.chi_lbl.setObjectName(_fromUtf8("chi_lbl"))
        self.gridLayout_2.addWidget(self.chi_lbl, 0, 2, 1, 1)
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.groupBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox_3.setTitle(_translate("Dialog", "DataFile", None))
        self.DataFileName_ledt.setToolTip(_translate("Dialog", "Select the Event Data file if not Live Data", None))
        self.DataFile_btn.setToolTip(_translate("Dialog", "Browse for the event file to be loaded.", None))
        self.DataFile_btn.setText(_translate("Dialog", "Browse", None))
        self.groupBox_9.setTitle(_translate("Dialog", "Peak Integration", None))
        self.peakRadius_lbl.setText(_translate("Dialog", "Radius of peak", None))
        self.peakRadius_ledt.setToolTip(_translate("Dialog", "Radius of peak to use for spherical integration (units of Q)", None))
        self.peakRadius_ledt.setText(_translate("Dialog", "0.15", None))
        self.groupBox_4.setTitle(_translate("Dialog", "CalibrationFile", None))
        self.CalFileName_ledt.setToolTip(_translate("Dialog", "Select the .DetCal file to apply.", None))
        self.CalFile_btn.setToolTip(_translate("Dialog", "Browse for the DetCal file to be loaded.", None))
        self.CalFile_btn.setText(_translate("Dialog", "Browse", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Corrections", None))
        self.linScatt_lbl.setText(_translate("Dialog", "linear scattering coeff", None))
        self.linAbs_ledt.setToolTip(_translate("Dialog", "True absorption linear absorption coefficent at 1.8 A in units of cm^-1", None))
        self.linAbs_ledt.setText(_translate("Dialog", "0", None))
        self.sampleRadius_ledt.setToolTip(_translate("Dialog", "Positve value of sample radius (cm) for absorption correction", None))
        self.sampleRadius_ledt.setText(_translate("Dialog", "0", None))
        self.linAbs_lbl.setText(_translate("Dialog", "linear absorption coeff", None))
        self.powerWavelength_lbl.setText(_translate("Dialog", "power of Wavelength", None))
        self.powerWavelength_ledt.setToolTip(_translate("Dialog", "Power of wavelength for Lorentz correction", None))
        self.powerWavelength_ledt.setText(_translate("Dialog", "4", None))
        self.sampleRadius_lbl.setText(_translate("Dialog", "sample radius", None))
        self.linScatt_ledt.setToolTip(_translate("Dialog", "Total scattering linear absorption coefficent in units of cm^-1 ", None))
        self.linScatt_ledt.setText(_translate("Dialog", "0", None))
        self.groupBox_10.setTitle(_translate("Dialog", "Plotting parameters", None))
        self.minIntensity_lbl.setText(_translate("Dialog", "Minimum intensity", None))
        self.minIntensity_ledt.setToolTip(_translate("Dialog", "Minimum intensity for plotting in reciprocal space", None))
        self.minIntensity_ledt.setText(_translate("Dialog", "100", None))
        self.numberGridPoints_lbl.setText(_translate("Dialog", "Number of grid points", None))
        self.numberGridPoints_ledt.setToolTip(_translate("Dialog", "Number of points in Qx, Qy, and Qz", None))
        self.numberGridPoints_ledt.setText(_translate("Dialog", "410", None))
        self.groupBox_8.setTitle(_translate("Dialog", "Find UB", None))
        self.PredictPeaks_rbtn.setToolTip(_translate("Dialog", "Use predicted peaks in data limits instead of found peaks", None))
        self.PredictPeaks_rbtn.setText(_translate("Dialog", "Predict Peaks", None))
        self.minABC_lbl.setText(_translate("Dialog", "minimum cell length", None))
        self.numberPeaks_ledt.setToolTip(_translate("Dialog", "Number of found peaks used to find UB", None))
        self.numberPeaks_ledt.setText(_translate("Dialog", "50", None))
        self.maxABC_ledt.setToolTip(_translate("Dialog", "Maximum cell length", None))
        self.maxABC_ledt.setText(_translate("Dialog", "11", None))
        self.maxABC_lbl.setText(_translate("Dialog", "maximum cell length", None))
        self.tolerance_lbl.setText(_translate("Dialog", "indexing tolerance", None))
        self.numberPeaks_lbl.setText(_translate("Dialog", "number of peaks to find", None))
        self.tolerance_ledt.setToolTip(_translate("Dialog", "Tolerance to use for indexing peaks", None))
        self.tolerance_ledt.setText(_translate("Dialog", "0.15", None))
        self.minABC_ledt.setToolTip(_translate("Dialog", "Minimun cell length", None))
        self.minABC_ledt.setText(_translate("Dialog", "3", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Data Limits", None))
        self.mindSpacing_lbl.setText(_translate("Dialog", "minimum dSpacing", None))
        self.mindSpacing_ledt.setToolTip(_translate("Dialog", "Minimum d-spacing", None))
        self.mindSpacing_ledt.setText(_translate("Dialog", "0.5", None))
        self.minWavelength_lbl.setText(_translate("Dialog", "minimum Wavelength", None))
        self.minWavelength_ledt.setToolTip(_translate("Dialog", "Minimum wavelength", None))
        self.minWavelength_ledt.setText(_translate("Dialog", "0.5", None))
        self.maxWavelength_lbl.setText(_translate("Dialog", "maximum Wavelength", None))
        self.maxWavelength_ledt.setToolTip(_translate("Dialog", "Maximum wavelength", None))
        self.maxWavelength_ledt.setText(_translate("Dialog", "3.5", None))
        self.minQspace_lbl.setText(_translate("Dialog", "minimum Qspace", None))
        self.minQspace_ledt.setToolTip(_translate("Dialog", "Minimum Qx, Qy, Qz", None))
        self.minQspace_ledt.setText(_translate("Dialog", "-20", None))
        self.maxQspace_lbl.setText(_translate("Dialog", "maximum QSpace", None))
        self.maxQspace_ledt.setToolTip(_translate("Dialog", "Maximum Qx, Qy, Qz", None))
        self.maxQspace_ledt.setText(_translate("Dialog", "20", None))
        self.groupBox.setTitle(_translate("Dialog", "LiveData", None))
        self.omega_ledt.setToolTip(_translate("Dialog", "Goniometer omegai angle if logs not available (degrees)", None))
        self.omega_ledt.setText(_translate("Dialog", "0", None))
        self.phi_lbl.setText(_translate("Dialog", "phi", None))
        self.phi_ledt.setToolTip(_translate("Dialog", "Goniometer phi angle if logs not available (degrees)", None))
        self.phi_ledt.setText(_translate("Dialog", "0", None))
        self.chi_ledt.setToolTip(_translate("Dialog", "Goniometer chi angle if logs not available (degrees)", None))
        self.chi_ledt.setText(_translate("Dialog", "135", None))
        self.omega_lbl.setText(_translate("Dialog", "omega", None))
        self.chi_lbl.setText(_translate("Dialog", "chi", None))

